---
- name: Allow SSH access only from ansible host and localhost
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - include_role: 
        name: 'allow-ssh-from-ansible-host-and-localhost'
