---
- name: Set password policy with PAM
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - include_role:
        name: 'set-password-policy-Debian'
    - include_role:
        name: 'set-password-policy-RedHat'
