---
- name: Set password policy without PAM
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - include_role:
        name: 'set-password-policy-without-PAM-RedHat'
    - include_role:
        name: 'set-password-policy-without-PAM-Debian'
 
