---
- name: Configure /etc/hosts.allow
  blockinfile:
    path: /etc/hosts.allow
    block: |
      sshd: 178.94.125.98, LOCAL
  register: result

- debug:
    msg: "{{ result }}"

- name: Configure /etc/hosts.deny
  blockinfile:
    path: /etc/hosts.deny
    block: |
      sshd: ALL
      ALL : ALL
  register: result

- debug:
    msg: "{{ result }}"

